### ISSUE TITLE
I can't find the segmentation dataset

### ISSUE THREAD

**Issue by gbinduo** [RViMLab/MICCAI2021_Cataract_semantic_segmentation#2]
Hi,
I can't find link to download the dataset. Is there any available link for downloading dataset?
Thank you very much!

**Comment by TheoPis** [comment]
Hi,
In order to get access to the dataset you need to first to join this challenge: https://cataracts-semantic-segmentation2020.grand-challenge.org/ and once your request is accepted by the organizers you will be able to find the data there. If that does not work, feel free to contact me by email (see paper for the email).

**Comment by TheoPis** [comment]
Hi,
In order to get access to the dataset you need to first to join this challenge: https://cataracts-semantic-segmentation2020.grand-challenge.org/ and once your request is accepted by the organizers you will be able to find the data there. If that does not work, feel free to contact me by email (see paper for the email).

**Comment by gbinduo** [comment]
Hi,

Thank you for the response. I really appreciate that.
I have submitted my request to join the challenge last month (August 22, 2023) and it's still being reviewed. I think the challenge no longer accept resquest. I really need the dataset for revising my paper to get it resubmitted in time. Therefore, could you pls help me out? I have sent you an email. Could you please check the mailbox? Thank you very much!!!
